### ISSUE TITLE
samples: "a reasonably complete and functional demo model"

### ISSUE THREAD

**Issue by timburks** [apigee/registry-experimental#187]
This will probably require multiple PRs and subtasks, but as a high-level goal, we would like to have at least one large example of a running API registry that includes the following:
- CI-based import of APIs from files in a git repository
- CI-based import of APIs from Apigee API management systems
- Automatic linting and scoring

Other optional features could include:
- Automatic conversion of API specs from a source format to desired derived formats
- Automatic generation of documentation and/or client libraries
- Automatic checks of registry completeness and correctness (via `registry check`)
- API governance-related checks (e.g. are all approvals documented?)
- Automated export to Backstage or similar internal developer portals

What would this look like? I've thought that we could put an example in a subdirectory of an existing repo or maybe create a new repo for an example, but increasingly I think this should be a multi-repo GitHub organization that represents a hypothetical enterprise's usage. It should include:
- Repos that contain API specs or Registry YAML that points to specs along with GitHub actions to automatically check these and import them into an API registry.
- Repos that build custom images that can be run as Kubernetes jobs and cronjobs to perform tasks on the registry including linting, scoring, and generation of resources.
- Repos that contain custom tools to import API information from various sources (git repos, services, API gateway management systems)
- Repos that store the output of controller actions: generated documentation and clients for internal and external users.
- Repos that store API services in progress to represent APIs in various stages of their lifecycles.
- Repos that support usage of Backstage and other developer portals including application code, configuration, and data staged for inclusion in these portals. 

To represent an actual organization's usage, most of these repos should be private to the organization and secured appropriately.

**Comment by theganyo** [comment]
I like this. However, if this is to be used as an example organization for demonstration and documentation purposes, "most of these repos should be private to the organization" won't be reasonable.

**Comment by timburks** [comment]
We now have [https://github.com/apigee-apihub-demo](apigee-apihub-demo). I'll digest the above bullet points into new issues in https://github.com/apigee-apihub-demo/apigee-apihub-demo.github.io/issues or more specific repos (all tracked in https://github.com/orgs/apigee-apihub-demo/projects/1/views/1).
